Database:
  Host: "localhost"
  Port: 3306
  Username: "NeverUseRoot"
  Password: "abcd1234"
  Database: "ranksql"
  Table: "ranksql"

Synchronisation:

  Triggers:
    Player-Join: true
    Player-Leave: true
    Delay: false # Not yet implemented
    Delay-Time: 6000 # In ticks

  Only-Current-Player: true

  Remove-Ranks-If-Not-In-DB:
    - vip
    - mod
    - admin
    - owner

  Download-Whitelist: # Not yet implemented
    - vip
    - mod
    - admin
    - owner

  Upload-Whitelist: # Not yet implemented
    - vip
    - mod
    - admin
    - owner