name: RankSql
version: Kat1.1
main: main.java.net.newtownia.ranksql.RankSQL
author: VincBreaker
authors: [MrKitty_Cat]

depend: [PermissionsEx]

commands:
  ranksql:
    description: 'Reload or force-synchronise ranksql.'
    usage: '/ranksql <reload|synchronise>'

permissions:
  ranksql.reload:
    default: OP
  ranksql.synchronise:
    default: OP